[package]
name = "package_name"
version = "0.0.0"

[addresses]
AptosFramework = "0x1"
OwningAccount = "0xe110"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework", rev = "0b834fc218648d759e93a7d61a432d0dce6c9946" }